# Generated by Django 6.0.1 on 2026-02-20 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0002_turf_additional_facilities_turf_facilities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='turf_images/')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='turfs.turf')),
            ],
        ),
    ]
