# Generated by Django 6.0.1 on 2026-02-20 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0003_turfimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_proof', models.FileField(upload_to='verification_docs/')),
                ('ownership_agreement', models.FileField(upload_to='verification_docs/')),
                ('municipal_permission', models.FileField(upload_to='verification_docs/')),
                ('gst_certificate', models.FileField(blank=True, null=True, upload_to='verification_docs/')),
                ('turf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='turfs.turf')),
            ],
        ),
    ]
