# Generated by Django 6.0.1 on 2026-02-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0004_verificationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
