# Generated by Django 4.2.28 on 2026-02-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0012_turf_opening_time_turf_turf_size_alter_booking_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='turf',
            name='turf_size',
        ),
    ]
